### ISSUE TITLE
Fix Image Size Issue

### ISSUE THREAD

**Issue by benjstorlie** [benjstorlie/pick-a-pic#18]
To make the image be contained in a variable-sized div, you can replace the image with a div with a background image styled like this:
```  
.img-div {
  /* background-image: url('path/to/image.jpg'); */
  background-size: contain;
  background-position: center center;
  background-repeat: no-repeat;
  background-clip: padding-box;
}
```
(I'm not sure exactly what `background-clip` should be set to.)
So instead of `$("#myImg").attr("src",src)`, do `$("#myImg").css("background-image, "url("+src+")")`.
[This article talks about how to deal with accessibility attributes.](http://www.davidmacd.com/blog/alternate-text-for-css-background-images.html).
I think the "img-div" is still allowed to have the same bootstrap classes like ".img-card-btm".

**Comment by markciubal** [comment]
Ibrahim is working on this one.

**Comment by benjstorlie** [comment]
Me: _If the background image of a div knows the size to be when background-size: contain, how come an image element in a div can't tell what size to be?_

ChatGPT:

> When using background-size: contain, the background image is scaled proportionally to fit inside the content box of the element (i.e., the width and height of the element excluding padding and border), while preserving the aspect ratio of the original image. This means that the size of the background image is determined by the size of the element that contains it.
> 
> On the other hand, when using an img element, the size of the image is determined by its intrinsic dimensions (i.e., the actual pixel dimensions of the image file), unless you specify a width or height explicitly using CSS. If you don't specify a width or height, the image will be displayed at its full size, which may cause it to overflow its parent element if the parent element is smaller than the image.
> 
> So, in the case of a background-image, the image size is determined by the element size, while in the case of an img element, the image size is determined by the intrinsic dimensions of the image file. This is why setting background-size: contain can be helpful when you want to ensure that the background image fits inside its containing element without stretching or overflowing, whereas with an img element, you need to explicitly set the size to prevent it from overflowing its container.

**Comment by benjstorlie** [comment]
Me: _I want everything to be constrained to the viewport.  Using flex, I have some divs that are sized to fit their content, and other divs that are sized to fill the rest of the space.  Inside the second kind of div, I have more divs that have some elements sized to fit content, and the rest stretch to fill the space.  But inside the element that is stretched to fill the space, I have an image.  I want the image to object-fit: constrain, but it can't tell how tall it's allowed to be, because the height of the div it's in was set to stretch to fill the remaining space.  So the image sometimes is too big, which ends up stretching out the whole grid._

ChatGPT:

> To constrain an image inside a div that has been set to stretch to fill the remaining space, you can set a max-height property on the image, equal to the height of the div. Here's an example of how you can accomplish this with Bootstrap and JavaScript:
> 
> HTML:

```
<div class="container-fluid d-flex flex-column" style="height: 100vh;">
   <div class="row flex-grow-1">
     <div class="col-sm-4 bg-primary d-flex flex-column justify-content-center align-items-center">
       <div class="content">
         <h1>Hello, world!</h1>
         <p>This is some sample content.</p>
       </div>
     </div>
     <div class="col-sm-8 bg-secondary d-flex flex-column justify-content-center align-items-center">
       <div class="content">
         <img src="https://via.placeholder.com/350x150" alt="Sample Image">
         <p>This is some more sample content.</p>
       </div>
     </div>
   </div>
 </div>
```
> In this example, we have a container that takes up the full height of the viewport (height: 100vh), with two columns inside that use flex-grow-1 to fill the remaining space. Inside the second column, we have an image that we want to constrain to fit inside the column.
> 
> JavaScript:

```
window.addEventListener('load', function() {
  const img = document.querySelector('.bg-secondary img');
  const container = document.querySelector('.bg-secondary');
  img.style.maxHeight = container.offsetHeight + 'px';
});
```
> In this JavaScript code, we're adding an event listener to the load event of the window to ensure that the image and container have loaded. Then, we're selecting the image and container using document.querySelector(), and setting the max-height of the image to the height of the container using offsetHeight.
> 
> With this code, the image will be constrained to fit inside the container, and the container will fill the remaining space in the viewport. Note that you may need to adjust the code to fit your specific layout and CSS classes.

Me: _What is offsetHeight?_

ChatGPT:

> offsetHeight is a property of the HTMLElement interface in JavaScript that represents the total height of an element, including the element's padding, border, and horizontal scrollbar (if any). It is a read-only property that returns a value in pixels, and it does not include the margin of the element.
> 
> In the context of the example I provided earlier, container.offsetHeight refers to the total height of the .bg-secondary element, including its padding and border. We are setting the max-height property of the image to this value so that the image will be constrained to fit inside the container without stretching beyond its bounds.
> 
> It's worth noting that offsetHeight can be affected by the element's display property, as well as other factors such as the box-sizing property and the presence of a horizontal scrollbar. Additionally, offsetHeight can trigger a reflow of the page layout, which can have performance implications, so it's generally a good idea to use it sparingly and only when necessary.
