### ISSUE TITLE
Button icons

### ISSUE THREAD

**Issue by benjstorlie** [benjstorlie/pick-a-pic#19]
Find some nice icons with font-awesome?  Or import Firefox emoji font?

**Comment by markciubal** [comment]
Mark is working on this one.

**Comment by benjstorlie** [comment]
[Here](https://github.com/mozilla/fxemoji) is where I got the emoji .svgs.  There should be a way to just import or download the font, and then the icons can just actually be text emojis, instead of a whole image.

**Comment by markciubal** [comment]
Keeping current icon setup with .svg files hard-coded into application.
