### ISSUE TITLE
Visual feedback when computer is speaking

### ISSUE THREAD

**Issue by benjstorlie** [benjstorlie/pick-a-pic#20]
For the deploy.html page.  Probably for the editor.html, too, since things are getting spoken there, too.

Add to the .click() event that triggers the speaking, `.addClass("active")`.

Style the `.myClass.active` in CSS to have some visual effect.

Need to add some time to `.removeClass("active")`.  Is there a way we know when it's done speaking?  Have it be removed after a set period of time?

**Comment by markciubal** [comment]
Mark is working on this one 5/1/2023.

**Comment by markciubal** [comment]
Completed for deployed pages.
